### ISSUE TITLE
Failure to install with steamnative

### ISSUE THREAD

**Issue by John-Gee** [xomachine/SteamForwarder#16] opened 2018-02-04 14:05 UTC
As asked on reddit:

I've used your aur package to build it, nothing else to configure anything (maybe that's the issue)

SF in the console:
app_install --steamnative -v 2 20900  --depot
Connecting to steam instance...
Steam process found
PID: <PID>
Command pipe: /home/john/.steam/steam.pipe
Output reader PID: <PID>
Volumes: [<1>, <2>, <3>]
Obtaining app info...
'oslist'
Failed to get appinfo via steamcmd, falling back to http method...
Depot downloading is not available with http method!
Generating manifest...
Downloading The Witcher: Enhanced Edition via steamcmd...
Downloading started! Check out your steam. When download is finished, run this script again with the same options and additional --no-download argument.

Steam console (that's big):

https://gist.github.com/John-Gee/ab5f85d6bf8dc48174fcb9eb31d42397

The last 2 lines seem related to the UI and not SteamForwarder

**Comment by xomachine** [comment] 2018-02-04 14:37
Are PIDs and Volumes hidden by you or they aren't exist in log?

**Comment by John-Gee** [comment] 2018-02-04 14:38
Yes by me :)

**Comment by xomachine** [comment] 2018-02-04 16:58
Hopefully, I've fixed it. Test with latest commit required.

**Comment by John-Gee** [comment] 2018-02-05 09:26
That seemed to have worked indeed!

Although it ended with this:

Generating the steam_api.dll wrapper just for this game...
Can not find steam_api.dll inside the game directory! Probably, the game is incompatible with SteamForwarder

Not sure if there is supposed to be that dll or not, I don't know if it supports Steam at all.

**Comment by xomachine** [comment] 2018-02-05 14:46
This message can be caused by one of reasons:

* The game is not installed at all (script failed to install the game and it passed to the next step)
* The game is installed but the steam_api.dll linked statically or not needed at all. In this case the game can be considered as incompatible.

The game should appear in the steam, so you can check if there are any files in its install directory.

**Comment by John-Gee** [comment] 2018-02-05 14:51
The game is correctly downloaded and installed I believe, so that message is nothing bad.

But starting it through Steam will lead to Steam complaining about an incompatible system to start the update, probably because of the lack of steam_api.dll. I guess this means it does not need Steam to run so downloading it is enough :)

How would I update it? (well not this game, but any game in a similar situation).

Thank you for the quick help!

**Comment by xomachine** [comment] 2018-02-05 15:27
The linux steam takes care about windows-only games updates. (e.g. it correctly updates Path Of Exile) but there can be problems with mac/windows games. Those games should be updated via SteamForwarder script. Only update will be downloaded without the `--depot` option (if anything will be downloaded at all).

There is a big chance of  download failure, so it is better to check manually if the game executable and/or steam_api.dll exists. Especially with `--steamnative` flag which was not tested much. E.g. Atlas Reactor can be installed only via `--depot`.

**Comment by John-Gee** [comment] 2018-02-05 15:45
Got it, thank you!

**Comment by xomachine** [comment] 2018-04-18 21:43
The first problem seems to be fixed, so I'm closing the issue.
If there is something left unresolved feel free to reopen it.

**Closed as completed by xomachine** 2018-04-18 21:43 UTC
Labels: bug, devel
