### ISSUE TITLE
Can't make using either method

### ISSUE THREAD

**Issue by Fluffkin** [xomachine/SteamForwarder#6] opened 2017-03-07 12:58 UTC
A simple make or make generate-code gives me the same errors on compile:

wineg++ -c  -m32 -fpermissive -Wno-attributes  -Isteam -I. -Iautoclass -D__WINESRC__ -DVERSION_SAFE_STEAM_API_INTERFACES -DUSE_BREAKPAD_HANDLER  -o autoclass/wrap_isteamclient.o autoclass/wrap_isteamclient.cpp
In file included from steam/steam_api.h:13:0,
                 from autoclass/steam_api_.h:3,
                 from autoclass/wrap_isteamclient.cpp:1:
steam/isteamclient.h:77:0: warning: "__cdecl" redefined
 #define __cdecl
 ^
<command-line>:0:0: note: this is the location of the previous definition
autoclass/wrap_isteamclient.cpp: In member function ‘virtual HSteamPipe ISteamClient_::CreateSteamPipe()’:
autoclass/wrap_isteamclient.cpp:6:8: error: ‘result’ does not name a type
   auto result = this->internal->CreateSteamPipe();
        ^
In file included from ./config.h:7:0,
                 from autoclass/steam_api_.h:4,
                 from autoclass/wrap_isteamclient.cpp:1:
autoclass/wrap_isteamclient.cpp:7:35: error: ‘result’ was not declared in this scope
   TRACE("() = (HSteamPipe )%p\n", result);
                                   ^
autoclass/wrap_isteamclient.cpp:9:10: error: ‘result’ was not declared in this scope
   return result;

**Comment by xomachine** [comment] 2017-03-07 22:08
Seems like your compiler does not support c++11 standart by default. I replaced the `auto` keyword in sources and code generator to actual types, so, please try to compile the latest version (don't forget to `git pull` latest changes)

**Comment by Fluffkin** [comment] 2017-03-08 01:04
Thank you, and almost!

callbacks.cpp:30:8: error: ‘result’ does not name a type
   auto result = this->internal->GetCallbackSizeBytes();

Seems to be the last one left.
(Can confirm it compiles fine with that last one changed)

**Comment by xomachine** [comment] 2017-03-08 11:09
I completely forgot about callbacks, they are written manually without code generator. Looks like the issue is fixed now. Please reopen it if I missed something else. Thank you for feedback!

**Closed as completed by xomachine** 2017-03-08 11:09 UTC
